language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tshark
script:
  - pip install -r requirements.txt
  - python src/setup.py install
  - py.test tests/
  
